### ISSUE TITLE
The project src in the project page repo (needs seperate repo)

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/www-project-safetypes#1]
Heya! Great project - one small observation:

Most projects have a git pages repo, and a repo for the actual project source code, for Example:

- The OWASP Amass project has its it's GitHub pages repo here https://github.com/OWASP/www-project-amass/blob/master/index.md
- The OWASP Amass project has it's source code here https://github.com/OWASP/Amass

Not a big issue, but would help differentiate the two and avoid pulling unnecessary files etc..

**Comment by todorolev** [comment]
Thank you @kerberosmansour. I'll create a separate repo for the source code. Thanks for the example.

**Comment by kerberosmansour** [comment]
Anytime, and thank you for your contributions to OSS.
