### ISSUE TITLE
Package Request - Place the Project on Maven Central

### ISSUE THREAD

**Issue by kerberosmansour** [OWASP/www-project-safetypes#2]
This is a really great project, I was wondering if there are any intentions to package the code and make it available on maven central so developers could easily find it?

**Comment by todorolev** [comment]
Thank you @kerberosmansour! Sure, this is the intention. I'll do my best to produce a deliverable in the next one or two weeks.

**Comment by kerberosmansour** [comment]
Awesome thanks!

**Comment by todorolev** [comment]
@kerberosmansour it took much more than planned, but I was exploring a new approach of validating. Anyway, version 1.0.0 is released now: https://mvnrepository.com/search?q=safetypes

**Comment by kerberosmansour** [comment]
Yay!! Thank you!
